### ISSUE TITLE
undefined values causing problems

### ISSUE THREAD

**Issue by dominictarr** [eugeneware/level-queryengine#1]
Problem at this line:

https://github.com/eugeneware/jsonquery-engine/blob/master/jsonquery-plan.js#L19

Maybe should just ignore it?

**Comment by eugeneware** [comment]
I've had a crack at fixing it in 0.0.5.

I assume you mean doing queries like:

``` js
var query = { mykey: undefined };
```

I've made a change to jsonquery-engine and to jsonquery to fix that case. Let me know if that works or whether you're referring to another use case.

**Comment by dominictarr** [comment]
cool, thanks!
