### ISSUE TITLE
Bug in key creation  "ÿindexesÿ[object Uint8Array]"

### ISSUE THREAD

**Issue by mehdi-cit** [eugeneware/level-queryengine#7]
Hello!
I tried to run a small test in the browser (latest chrome, but the same problem in both Firefox and IE11) and got an error. It seems the code that creates keys for the indexed fields is failing.
Note that it works fine if I do not use indexing. //db.ensureIndex('name');

Here's the code:

---

var levelQuery = require('level-queryengine'),
    jsonqueryEngine = require('jsonquery-engine'),
    leveljs  = require('level-js'),
    levelup = require('levelup');

```
window.db = levelQuery(levelup('my-db', { db: leveljs }));
db.query.use(jsonqueryEngine());
db.ensureIndex('name');
```

 var customerData = [
        { type: 'put', key: 'a', value: { ssn: "444-44-4444", name: "Bill", age: 35, email: "bill@company.com" }},
        { type: 'put', key: 'b', value: { ssn: "555-55-5555", name: "Donna", age: 32, email: "donna@home.org" }}
    ];
db.batch(customerData, function (err) {
      if (err) return console.log('Ooops!', err)
      console.log('Great success dear leader!')
    })

---

The result in indexeddb is displayed below:

Key:    "a"
Value: {ssn:444-44-4444, name:Bill, age:35, email:bill@company.com}

Key:    "b"
Value: {ssn:555-55-5555, name:Donna, age:32, email:donna@home.org}

Key:     "ÿindexesÿ[object Uint8Array]"
Value:  "b"

---

I wasn't able to get enough understanding of the code to try and fix the problem. But the following link can give a hint (check  line 1260: Class: ProxyBuffe): 
https://github.com/mgutz/plv8-bedrock/blob/master/migrations/201312220022-plv8-startup/up.sql

I hope someone can help make sense of this.

Cheers~

**Comment by mehdi-cit** [comment]
For anyone reading this. It seems the problem is that bytewise (https://github.com/deanlandolt/bytewise) is not supported on browser yet! It won't behave correctly (cannot properly encode/decode)

**Comment by eugeneware** [comment]
Thanks @mehdi-cit - I suspected that's what the issue would be. Probably worth opening an issue on their package. With the new Buffer stuff in browserify, there shouldn't be any real good reason for it not to work I would think.

**Comment by mehdi-cit** [comment]
Hello Eugene!
First, thank you for sharing your your different npm with the rest of us!
The problem seems to originate from bops that's used by bytewise. 
See the issue I opened here:
https://github.com/chrisdickinson/bops/issues/13
I'll set this issue as closed. I might get back to it if I find something worth sharing.
On a different note. For readers interested in using Indexeddb on the browser, you may find Dexie.js interesting. It'd been better to use leveljs but some might still find dexie.js worth a shot.
https://github.com/dfahlander/Dexie.js

**Comment by mehdi-cit** [comment]
Ok! I had the time to look at it this afternoon and the problem I had was related to a chrome extension (so nothing to do with the solution, just l´my local chrome installation).
Finally it seems jsonquery-engine can work in the browser (just tested a simplified version of example https://github.com/eugeneware/jsonquery-engine/blob/master/test/level-plan.js  in the latest chrome).
Simply put, one has to use https://github.com/feross/buffer in https://github.com/chrisdickinson/bops instead of typedarray.
Here are the steps to make it work in the browser (browserify):. 
npm install jsonquery-engine 
npm install level-queryengine
Go up the npm modules until you reach:
node_modules\level-queryengine\node_modules\subindex\node_modules\bytewise\node_modules\bops
open package json file and make sure browser entry is as follows:
"browser": {
    "./copy.js": "./copy.js",
    "./create.js": "./create.js",
    "./from.js": "./from.js",
    "./join.js": "./join.js",
    "./mapped.js": "./mapped.js",
    "./read.js": "./read.js",
    "./subarray.js": "./subarray.js",
    "./to.js": "./to.js",
    "./is.js": "./is.js",
    "./write.js": "./write.js"
  },
In the above, we simply tell it not to use typedarray when it detects it's running on the browser.
So "./copy.js": "./typedarray/copy.js", becomes "./copy.js": "./copy.js",
now:
npm install buffer
See https://github.com/feross/buffer
Now open all .js files and make sure Buffer is set as shown below
var Buffer = require('buffer/').Buffer
and no longer:
var Buffer = require('buffer').Buffer

Voila! that should be it
